appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'


urlpatterns = [
    path('create_appontment/', views.BookAppointmentView, name='create_appontment'),
    path('appointment_list/', views.AppointmentListView.as_view(), name='appointment_list'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('create/', views.CreateBlogView, name='create_post'),
    path('<slug>/', views.BlogDetailView, name='detail_post'),
    # path('<slug>/edit', views.EditBlogView, name='edit'),
]

clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('account.urls')),
    path('blog/', include('blog.urls')),
    path('appointment/', include('appointment.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    profile = models.ImageField(null=True, blank=True, upload_to = "images/" ) 
    address = models.TextField(max_length=200) 
    city = models.CharField(max_length=50) 
    state = models.CharField(max_length=50)  
    pincode = models.CharField(max_length=50)

    def __str__(self):
        return self.username

class Patient(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)

    def __str__(self):
        return str(self.user.username)

class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    
    def __str__(self):
        return str(self.user.username)

templates/appointment_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container">
    <div class="row">
        <!-- For Header -->
        {% if not request.user.is_authenticated %}
        <div class="col-lg-12">
            <h1 class="text-center mt-5 mb-5">Welcome To Clinic</h1>
        </div>
        <div class="container">
            <div class="d-flex flex-column">
                <p class="m-auto">
                    <a class="btn btn-warning" href="{% url 'register' %}">Register</a> or 
                    <a class="btn btn-warning" href="{% url 'login' %}">Login</a>
                </p>
            </div>
        </div>
        <!-- End For Header -->
        {% else %}
        <div class="col-lg-12">
            <h1 class="text-center mt-5 mb-5">Welcome To Clinic</h1>
        </div>
        <div class="container bg-light mt-4 pt-3 pb-3">
                <div class="col-lg-8">
                    <b class="text-secondary">All Appointment for DR.{{request.user.get_full_name}}</b><br>
                    {% if user.is_doctor %}
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            <div class="list-group">
                                {% for apt in appointment %}
                                <div class="col-rg-10 mg-4">
                                    <div class="card">
                                        <div class="card-body">
                                            <h5>Name: {{apt.appointment_user.get_full_name}}</h5>
                                            <h5>Required Speciality: {{apt.required_speciality}}</h5>
                                            <h5>Date of Appointment: {{apt.date_of_Appointment}}</h5>
                                            <h5>Start Time of Appointment: {{apt.start_Time_of_Appointment}}</h5>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}

    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% load static %}
    {% block head %}{% endblock %}

</head>
<body>

    <!-- Nav Bar -->
    <nav class="navbar {% if not request.user.is_authenticated %} navbar-expand-lg {% endif %} navbar-light bg-warning">
        <a class="navbar-brand" href="/">Clinic</a>
        {% if not request.user.is_authenticated %}
        {% else %}
        <form action="" class="form-inline">
            <span class="mr-4" >{{ request.user.get_full_name|title }}</span>

            {% if request.user.is_patient %}
            <a href="{% url 'doctor_list' %}" class="btn btn-outline-dark mr-1">All Doctors</a>
            {% endif %}
            
            {% if request.user.is_doctor %}
            <a href="{% url 'appointment:appointment_list' %}" class="btn btn-outline-dark mr-1">All Appointment</a>
            {% endif %}

            <a href="{% url 'logout' %}" class="btn btn-outline-dark mr-1" >Sign Out</a>
        </form>

        {% endif %}
    </nav>
    {% block content %}{% endblock %}
    <!-- End Nav Bar -->
    <!-- Footer -->
    <footer class="text-center mt-5 mb-5">
        &copy;clinic@mail.com
    </footer>
    <!-- END Footer -->
</body>
</html>

templates/create_appointment.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Book Appointment{% endblock title %}

{% block content %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-7 offset-lg-1">
              <form class="create-form"  method="POST" enctype="multipart/form-data">{% csrf_token %}
  
                <!-- {{ form }}    -->
                {% bootstrap_form form %}
  
                <!-- Submit btn -->
                <button class="submit-button btn btn-lg btn-warning btn-block" type="submit">BOOK Appointment</button>
              </form>	
          </div>
      </div>
  </div>
  

{% endblock %}

templates/doctor_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container">
    <div class="row">
        <!-- For Header -->
        {% if not request.user.is_authenticated %}
        <div class="col-lg-12">
            <h1 class="text-center mt-5 mb-5">Welcome To Clinic</h1>
        </div>
        <div class="container">
            <div class="d-flex flex-column">
                <p class="m-auto">
                    <a class="btn btn-warning" href="{% url 'register' %}">Register</a> or 
                    <a class="btn btn-warning" href="{% url 'login' %}">Login</a>
                </p>
            </div>
        </div>
        <!-- End For Header -->
        {% else %}
        <div class="col-lg-12">
            <h1 class="text-center mt-5 mb-5">Welcome To Clinic</h1>
        </div>
        <div class="container bg-light mt-4 pt-3 pb-3">
                <div class="col-lg-8">
                    <b class="text-secondary">All Doctors</b><br>
                    {% if user.is_patient %}
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            <div class="list-group">
                                {% for doctor in all_doctors %}
                                {% if doctor.is_doctor %}
                                    <div class="col-rg-10 mg-4">
                                        <div class="card">
                                            <div class="card-body">
                                                <img src="{{doctor.profile.url}}" alt="Doctor Image" class="rounded-circle mb-2" width="150" height="150">
                                                <hr>
                                                <h5>Name: {{doctor.get_full_name}}</h5>
                                                <h5>E-Mail: {{doctor.email}}</h5>
                                                <a class="btn btn-warning mr-1 mt-2" href="{% url 'appointment:create_appontment' %}">Book Appointment</a>
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}

    </div>
</div>

{% endblock %}

templates/doctor_sign_up.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

{% if not request.user.is_authenticated %}
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h2>Doctor sign Up</h2>
                        <hr>
                        <form action="{% url 'doctor_register' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.media }}
                            {% bootstrap_form form %}
                            <button type="submit" class="btn btn-warning btn-block">Sign Up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container">
    <div class="row">
        <!-- For Header -->
        {% if not request.user.is_authenticated %}
        <div class="col-lg-12">
            <h1 class="text-center mt-5 mb-5">Welcome To Clinic</h1>
        </div>
        <div class="container">
            <div class="d-flex flex-column">
                <p class="m-auto">
                    <a class="btn btn-warning" href="{% url 'register' %}">Register</a> or 
                    <a class="btn btn-warning" href="{% url 'login' %}">Login</a>
                </p>
            </div>
        </div>
        <!-- End For Header -->
        {% else %}
        <div class="col-lg-12">
            <h1 class="text-center mt-5 mb-5">Welcome To Clinic</h1>
        </div>
        <div class="container bg-light mt-4 pt-3 pb-3">
            <div class="row">
                <div class="col-lg-4">
                    <div class="text-center">
                        <h2>DashBoard</h2>
                        <hr>
                        <!-- <img src="{% static 'images/profile.png' %}" alt="" class="rounded-circle mb-2" width="100" height="100"> -->
                        <img src="{{ user.profile.url }}" alt="" class="rounded-circle mb-2" width="100" height="100">
                        <h4>{{ request.user.get_full_name }}</h4>
                        <p class="text-secondary">{{ request.user.email }}</p>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">{{ request.user.username }}</li>
                        <li class="list-group-item">{{ request.user.address }}</li>
                        <li class="list-group-item">{{ request.user.city }}</li>
                        <li class="list-group-item">{{ request.user.state }}</li>
                        <li class="list-group-item">{{ request.user.pincode }}</li>                        
                    </ul>
                    <hr>
                    {% if request.user.is_doctor %}
                    <a class="btn btn-warning mr-1 mt-2" href="{% url 'blog:create_post' %}">Create Blog</a>
                    {% endif %}
                </div>
                <div class="col-lg-8">
                    <b class="text-secondary">Blogs</b><br>
                    {% if blog_posts %}
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            <div class="list-group">
                                {% for post in blog_posts %}
                                    {% if request.user.is_doctor %}
                                        {% if post.author == request.user %}
                                            <a href="{% url 'blog:detail_post' post.slug %}" class="list-group-item list-group-item-action flex-column align-items-start bg-warning text-black">
                                                <div class="d-flex w-100 justify-content-between">
                                                    <h5 class="mb-1">{{post.title}}</h5>
                                                    <small>{{ post.date_published }}</small>
                                                </div>
                                                <p class="mb-1">{{post.summery|safe|truncatechars:120}}</p>
                                            </a>
                                            <hr>
                                        {% endif %}
                                    {% else %}
                                        <a href="{% url 'blog:detail_post' post.slug %}" class="list-group-item list-group-item-action flex-column align-items-start bg-warning text-black">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-1">{{post.title}}</h5>
                                                <small>{{ post.date_published }}</small>
                                            </div>
                                            <p class="mb-1">{{post.summery|safe|truncatechars:120}}</p>
                                        </a>
                                        <hr>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% else %}
                        {% if request.user.is_doctor %}
                        <p>You Have no Post Create a post <a href="{% url 'blog:create_post' %}">here</a></p>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}

    </div>
</div>

{% endblock %}

templates/patient_sign_up.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

{% if not request.user.is_authenticated %}
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h2>Patient sign Up</h2>
                        <hr>
                        <form action="{% url 'patient_register' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.media }}
                            {% bootstrap_form form %}
                            <button type="submit" class="btn btn-warning btn-block">Sign Up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}

{% if not request.user.is_authenticated %}

    <div class="container mt-5">
        <div class="row">
            <!-- For Header -->
            <div class="container">
                <div class="d-flex flex-column">
                    <p class="m-auto">
                        <a class="btn btn-warning" href="{% url 'patient_register' %}">Patient</a> or 
                        <a class="btn btn-warning" href="{% url 'doctor_register' %}">Doctor</a>
                    </p>
                </div>
            </div>
            <!-- End For Header -->
        </div>
    </div>
{% endif %}


{% endblock %}

templates/sign_in.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

{% if not request.user.is_authenticated %}

<div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'login' %}" method="post">
                        {% csrf_token %}
                        {% bootstrap_form_errors form %}
                        {% bootstrap_label "Email" %}
                        {% bootstrap_field form.username show_label=False placeholder="Email" %}
                        {% bootstrap_field form.password %}
                        <button class="btn btn-warning btn-block">Sign In</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endif %}

{% endblock %}